### PR TITLE
Copying PS3 support and other fixes

### PR DESCRIPTION
**Pull request by victorvogelpoel**

### CODE REVIEW

**Comment by victorvogelpoel** [comment]
Aj, that wasn't my intention... Closing pull request...

**Comment by KirkMunro** [comment]
I'm confused.  What wasn't your intention?  Submitting a pull request?  Or
closing the pull request?

## 

*Kirk Munro *
Poshoholic, Microsoft MVP
Blog http://poshoholic.com/ | Twitter http://twitter.com/poshoholic |
LinkedIn http://ca.linkedin.com/in/kirkmunro | GitHub
http://github.com/KirkMunro | Facebook
http://www.facebook.com/#%21/kirk.munro

Need a PowerShell SME for a project at work? Contact me
http://poshoholic.com/contact-me/!

**Comment by victorvogelpoel** [comment]
From GIT confusion to communication confusion...
I wanted to merge your PS3 compatibility changes with my fork of the PowerShell/PSScriptAnalyzer, eq sync your fork+changes to mine. A pull request should be able to do that, but the PR I created did not. If I am reading the PR summary correctly, the PR says it'll merge the PowerShell:master into KirkMunro:master instead of merging the KirkMunro:master into victorvogelpoel:master.

Instead,I deleted my VictorVogelpoel/PSScriptAnalyzer fork and forked your KirkMunro/PSScriptAnalyzer to get your changes.

**Comment by KirkMunro** [comment]
Ok, that works. I haven't had to pull code together from multiple forks
yet. Fun? :)

## 

*Kirk Munro *
Poshoholic, Microsoft MVP
Blog http://poshoholic.com/ | Twitter http://twitter.com/poshoholic |
LinkedIn http://ca.linkedin.com/in/kirkmunro | GitHub
http://github.com/KirkMunro | Facebook
http://www.facebook.com/#%21/kirk.munro

Need a PowerShell SME for a project at work? Contact me
http://poshoholic.com/contact-me/!

**Comment by victorvogelpoel** [comment]
I think its possible in Git to define multiple remotes and sync changes between each. I think I have to learn how to reverse screw-ups first before engaging in advanced GIT.

**Pull request closed without merging**
